% List of open inputs
nrun = 1; % enter the number of runs here
spm('defaults', 'FMRI');
clear jobs;
spm_jobman('initcfg');

jobs = {'~/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job40000.m'};

    %'/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job2500.m'
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job5000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job10000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job20000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job40000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job80000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job160000.m',...
%         '/home/felipe/PermTest/SnPM-output/TwoSample_ADRCRuns/ADRCRun_job320000.m',...
 %       };
    
inputs = cell(0, nrun);

spm('defaults', 'FMRI');
spm_jobman('run', jobs, inputs{:});
